name: Later Gator
on:
  pull_request:
    types: [labeled]

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    if: github.event.label.name == 'later gator'
    permissions:
      issues: write
      repository-projects: write
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Create team sync issue
        run: |
          echo $(gh project list --format json --owner ${{ github.repository_owner }})
          gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          GH_REPO: ${{ github.repository }}
          TITLE: 後ほど対応： ${{ github.event.pull_request.title }}
          ASSIGNEES: ${{ github.event.sender.login }}
          LABELS: not now but soon
          BODY: |
            ### 対応するPR

            - ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}

          PROJECT_NO: 2
  PR_convert_to_draft:
    name: Convert PR to draft
    runs-on: ubuntu-latest
    if: github.event.label.name == 'later gator'
    needs: create_issue
    permissions:
      pull-requests: write
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Convert PR to draft
        run: |
          gh pr ready ${{ github.event.pull_request.number }} --undo
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          GH_REPO: ${{ github.repository }}
